name: Deploy docs to GitHub pages

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  deploy:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install -E web
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Build and deploy
        run: |
          poetry run portray on_github_pages --force --ignore_version
